# Generated by Django 4.2.3 on 2023-07-20 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('date_made', models.DateTimeField(verbose_name='date project made')),
                ('category', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images/')),
                ('submitted_date', models.DateTimeField(verbose_name='date submited')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
