# Generated by Django 4.2.3 on 2023-07-22 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contact_info',
            field=models.CharField(default='No contact info', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='related_links',
            field=models.CharField(default='No related links', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='sub_category',
            field=models.CharField(default='No sub category', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='team',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='submitted_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date submited'),
        ),
    ]
