# Generated by Django 4.2.3 on 2023-07-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_project_contact_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='entity',
            field=models.CharField(blank=True, default='No entity', max_length=200),
        ),
    ]
